# Generated by Django 4.2.11 on 2024-09-14 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_admin', '0003_alter_filmwork_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmwork',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='filmwork',
            name='file_path',
        ),
    ]
